#!/usr/bin/env bash
### setzer-deploy -- Deploy a new oracle contract
### Usage: setzer deploy <pair> [--quorum <number>]
###
### Deploy a medianizer oracle for <pair> and set
### initial bar to <quorum> if specified (default: 1)
set -e
[ $# -eq 1 ] || setzer --bad-usage "$0"
pair=$(setzer --pair "$1")
median=$(dirname "$0")/../../lib/median

tmp=$(mktemp -d)
mkdir "$tmp"/src
cp "$median/src/median.sol" "$tmp"/src
cd "$tmp"

sed -i.bk '/modifier toll/d' src/median.sol
sed -i.bk "s/ethusd/${pair,,}/
s/bar = 1/bar = ${SETZER_QUORUM}/;s/toll //g" src/median.sol
sed -i.bk -e '/function kiss.*/{N;N;N;N;d;}' src/median.sol
sed -i.bk -e '/function diss.*/{N;N;d;}' src/median.sol

dapp build --extract
export ETH_GAS=${ETH_GAS:-1500000}
dapp create Median
