#!/usr/bin/env bash
set -e
p1=${1:-8008}
p2=$(( p1 + 100 ))
json=$(jq -n --arg port1 "$p1" --arg port2 "$p2" \
'{
  "caps": {
    "shs": "DKPjSw4saYpF6tOdO8QzpOCioO10CVBU5g0OOghCD6w=",
    "sign": "UIBaKSSFLeie93K0ECAL7z78cSGXQIP+Y13sdLQY52k="
  },
  "host": "localhost",
  "port": $port1,
  "ws": {
    "port": $port2
  }
}')
echo "$json" | jq '.'
