#!/usr/bin/env bash
set -e

[[ $(pgrep -fq dapp-testnet) -eq 1 ]] && pkill -f dapp-testnet

dapp testnet &
pid="$!"
echo $pid
echo "Background jobs: $(jobs) "

from=$(seth accounts ls | sed 1q | awk '{print substr ($0, 0, 42)}')

export ETH_RPC_URL=http://127.0.0.1:8545
export ETH_KEYSTORE=$HOME/.dapp/testnet/8545/keystore
export ETH_FROM=$from
export ETH_PASSWORD=/dev/null

oracle=$(setzer deploy eth)
seth send "$oracle" 'lift(address)' "$ETH_FROM"

cat <<.
export ETH_RPC_URL=$ETH_RPC_URL
export ETH_FROM=$ETH_FROM
export ETH_KEYSTORE=$ETH_KEYSTORE
export ETH_PASSWORD=$ETH_PASSWORD

export TESTNET_ORACLE=$oracle
export SETZER_QUORUM=1
.

# export SETZER_QUORUM=1
# export ssb_appname="ssb-testnet"

# setzer-broadcast eth &
# broadcast=$!

# function clean() { ( set -x; kill $broadcast ); }
# trap clean EXIT SIGINT

# tail -f "$SETZER_DIR/broadcast.log"
