#!/usr/bin/env bash
### setzer-latest -- Print most recent quorum price messages for a pair
### Usage: setzer latest <pair> [address]
set -e
[ $# -gt 0 ] || setzer --bad-usage "$0"
pair=$(setzer --pair "$1")
[[ "$2" ]] && oracle=$(seth --to-address "$2")

valid()
{
    a=$(echo "$1" | jq -r '.author')
    if [[ ! $authors = *"$a"* ]]
    then
      authors+=$a
      setzer --valid-message "$1" "$oracle"
    fi
}

inc=0
for msg in $(setzer ssb messages "${pair^^}" | jq -c '.|.value'); do

  msg=$(valid "$msg")
  if [[ -n "$msg" ]]; then
    inc=$((inc+1))
    echo "$msg" | jq '.'
  fi

  [[ "$inc" -eq "$SETZER_QUORUM" ]] && break
done
