#!/usr/bin/env bash
### setzer-broadcast -- Broadcast signed prices over ssb
### Usage: setzer broadcast [<opts>] [--interval] <pair>
###
### Continously publish signed prices over ssb
###
### With `--interval', override the default update interval
set -e
_jq()   { echo "$msg" | jq -r ".value$1"; }
_date() { printf '%(%Y-%m-%d %H:%M:%S)T\n' $(( ${1::13} / 1000 )); }

if [[ $# -eq 1 ]]
then
  pair=$(setzer --pair "$1")
  while true
  do
    price=$(setzer price "$pair" median)
    msg=$(setzer ssb publish "$pair" "$price" "median")
    echo "$( _date "$(_jq '.timestamp')") ${pair^^} $(_jq '.content.price')"
    sleep "$SETZER_BROADCAST_INTERVAL"
  done
else
  setzer broadcast-bot "$@"
fi
