#!/usr/bin/env bash
set -e

command -v ssb-server >/dev/null 2>&1 || {
  echo >&2 "Error: ssb-server not installed.";
  exit 1
}

log() { echo  "$1" >> "$SETZER_DIR/ssb.log"; }

# shellcheck disable=SC2154
if [[ -z "$(pgrep -f "ssb-server start")" ]]; then
  if [[ ! -e "$HOME/.$ssb_appname/config" ]]; then
    setzer --ssb-conf > "$HOME/.$ssb_appname/config"
  fi

  nohup ssb-server start >> "$SETZER_DIR/ssb.log" 2>&1 &
  log "Starting ssb-server [$ssb_appname] $!" && sleep 1
fi

case $1 in
  id|public) {
    ssb-server whoami
  };;
  server) {
    ssb-server getAddress
  };;
  stop) {
    if [[ -n "$(pgrep -f "ssb-server start")" ]]; then
      log "Stopping ssb-server [$ssb_appname]"
      pkill -f "ssb-server start"
    fi
  };;
  publish) {
    pair=${2^^}; price=$3; src=$4
    setzer --to-msg "$pair" "$price" "$src" | ssb-server publish .
  };;
  messages) {
    if [[ "$SETZER_AGE" ]]; then
      age=$(( "$SETZER_AGE" * 1000))
    else
      now=$(( $(date +'%s * 1000 + %-N / 1000000') ))
      age=$(( now - ("$SETZER_MSG_AGE" * 1000) ))
    fi
    ssb-server messagesByType --type "$2" --gte "$age" --reverse
  };;
  "") {
    setzer help ssb
  };;
  *) {
    ssb-server "$@"
  };;
esac
