#!/usr/bin/env bash
### setzer-latest -- Print most recent quorum price messages for a pair
### Usage: setzer latest <pair> [address]
set -e
[ $# -gt 0 ] || setzer --bad-usage "$0"
pair=$(setzer --pair "$1")
[[ "$2" ]] && oracle=$(seth --to-address "$2")

previous()
{
    local msg; local key
    msg=$(setzer ssb get "$2")
    valid "$msg"
    if [ "$1" -lt "$SETZER_QUORUM" ]
    then
      key=$(echo "$msg" | jq -r '.previous')
      previous $(($1 + 1)) "$key"
    fi
}

valid()
{
    a=$(echo "$1" | jq -r '.author')
    if [[ ! $authors = *"$a"* ]]
    then
      authors+=$a
      setzer --valid-message "$1" "$oracle"
    fi
}

msg=$(head -n 1 <(setzer ssb messages "${pair^^}" | jq -c '.|.value'))
if [[ -n "$msg" ]]
then
  key=$(echo "$msg" | jq -r '.previous')
  valid "$msg"
  previous 2 "$key"
else
  echo >&2 "Error: no valid $pair prices"
  exit 1
fi
